swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"
basePath: "/api"

# Paths supported by the server application
paths:
  /ml_predict:
    get:
      operationId: "ml_predict.machine_learning.predict"
      parameters:
        - name: N
          description: "Number of predictions"
          in: query
          type: integer
          required: true
        - name: typ
          description: "Number of predictions"
          in: query
          type: integer
          required: false
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                responsetime:
                  type: string
                  description: The response time.
                elements:
                  type: string
                  description: The number of elementse.
  /ml_predict_data:
    post:
      operationId: "ml_predict.machine_learning.predict_data"
      parameters:
        - name: N
          description: "Number of predictions"
          in: query
          type: integer
          required: true
        - name: typ
          description: "Type of ML algorithm"
          in: query
          type: integer
          required: false
        - in: formData
          name: upfile
          type: file
          description: "The file to upload."
      produces:
        - application/json
      consumes:
        - multipart/form-data
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                responsetime:
                  type: string
                  description: The response time.
                elements:
                  type: string
                  description: The number of elementse.